# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        NCbrtBundle\Entity\User:
            algorithm: bcrypt

    providers:
        ncbrt_user_provider:
            entity:
                class: NCbrtBundle:User

    role_hierarchy:
        ROLE_USER:          ROLE_VIEW
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            provider: ncbrt_user_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                use_referer: true
            logout: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/checkreport, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backup$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }